name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-linux:
    strategy:
      fail-fast: false
      matrix:
        ruby: [3.2, 3.3, 3.4, 4.0]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Install dependencies
        run: bundle install
      - name: Run tests
        run: bundle exec rspec

  test-macos:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
        ruby: [3.2, 4.0]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Install shared-mime-info for mimemagic
        run: brew install shared-mime-info
      - uses: actions/checkout@v7
      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Install dependencies
        run: bundle install
      - name: Run tests
        run: bundle exec rspec

  test-windows:
    strategy:
      fail-fast: false
      matrix:
        ruby: [3.2, 4.0]

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v7
      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Install dependencies
        run: bundle install
      - name: Run tests
        run: bundle exec rspec
